#
# Makefile para programas de teste
# 

CC=gcc
LIB_DIR=../lib
CFLAGS=-lt2fs -Wall -m32

all: 

# Exemplo:
# testa_yield: teste.c $(LIB_DIR)/teste.a
#	$(CC) -o teste teste.c -L$(LIB_DIR) $(CFLAGS)


.PHONY: all clean 
	
clean:
	rm -rf *.o *~
